## NumPy Tutorial

In [3]:
import numpy as np

In [68]:
a=np.array([3,4,78,54])  # 1 Dimentional Array ------

In [3]:
a

array([ 3,  4, 78, 54], dtype=int16)

In [4]:
a[1]               # selecting array element---------

4

In [58]:
b=np.array([[3,5,73],[1,3,55]])                     # 2 Dimentional Array--------
b1=np.array([[2,7,88],[34,677,56],[98,7,66]]) 

In [60]:
b, b1

(array([[ 3,  5, 73],
        [ 1,  3, 55]]),
 array([[  2,   7,  88],
        [ 34, 677,  56],
        [ 98,   7,  66]]))

In [36]:
a.shape

(4,)

In [64]:
b.shape  , b1.shape

((2, 3), (3, 3))

In [76]:
a.dtype

dtype('int32')

## There are 6 general mechanisms for creating arrays:---------

####  1.  Conversion from other Python structures (i.e. lists and tuples)-----------

In [24]:
my_list=[1,2,4],[3,66,8],[33,88,66]
my_list

([1, 2, 4], [3, 66, 8], [33, 88, 66])

In [30]:
listarray=np.array(my_list)

In [32]:
listarray

array([[ 1,  2,  4],
       [ 3, 66,  8],
       [33, 88, 66]])

In [34]:
listarray.shape

(3, 3)

In [36]:
listarray.dtype

dtype('int32')

In [38]:
listarray.size

9

#### 2.  Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

#### 1. Zeros() -----------

In [42]:
zeros=np.zeros((2,5))

zeros

In [48]:
zeros.dtype

dtype('float64')

In [50]:
zeros.shape

(2, 5)

In [52]:
zeros.size

10

#### 2.  arange() ----

In [58]:
rng= np.arange(15)

In [60]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
rng.dtype

dtype('int32')

In [68]:
rng.size

15

In [70]:
rng.shape

(15,)

#### 3.  linspace() ------

In [86]:
lin=np.linspace(1,10,5);  lin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [88]:
lin.shape

(5,)

#### 4.  empty()------

In [95]:
emp=np.empty((2,3));  emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [4.45039557e-307, 1.89146896e-307, 7.56571288e-307]])

#### 5.   empty_like()---

In [102]:
emp1=np.empty_like(lin);   emp1    # here it will take size of lin and print random num. in it

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [104]:
emp1.shape

(5,)

In [108]:
emp1.dtype

dtype('float64')

#### 6.  identity() ------

In [115]:
iden=np.identity(5);  iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [117]:
iden.shape

(5, 5)

#### 7.  reshape() --------

In [189]:
arr1=np.arange(30);  arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [199]:
a=arr1.reshape(3,10)

In [201]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [203]:
a.shape

(3, 10)

In [213]:
b=a.ravel(); b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [215]:
b.shape

(30,)

### Axis in NumPy------
* axis = 0  It is a Row that works in a downward direction

* axis = 1  It is a column that works in an upward direction

In [222]:
x=([1,2,3],[4,5,6],[7,6,8])

In [226]:
array=np.array(x); array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 8]])

In [234]:
sum=np.sum(array,axis=0); sum   # sum of 1+4+7 , 2+5+6 , 3+6+8  

array([12, 13, 17])

In [238]:
sum=np.sum(array,axis=1); sum   # sum of 1+2+3 , 4+5+6 , 7+6+8

array([ 6, 15, 21])

#### Transpose array ----------

In [243]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 8]])

In [249]:
array.T         # Transpose array  row <-> column

array([[1, 4, 7],
       [2, 5, 6],
       [3, 6, 8]])

#### Flat method ---------

In [251]:
array.flat

In [255]:
for item in array.flat:          # this method will return all value in single column
    print(item)

1
2
3
4
5
6
7
6
8


#### ndim() ----------- it will return the number of dimention array( 1D, 2D, 3D etc.)

In [266]:
array.ndim

2

In [270]:
array.size

9

In [276]:
array.nbytes     # total menory accupy in bytes

36

#### argmax(), argmin() and argsort() function----------

In [20]:
a=np.array([2,5,77,44,3,9]); a

array([ 2,  5, 77, 44,  3,  9])

In [6]:
a.argmax()

2

In [8]:
a.argmin()

0

In [10]:
a.argsort()

array([0, 4, 1, 5, 3, 2], dtype=int64)

In [5]:
a1=np.array([[3,656,46],[6,9,55],[2,67,34]])

In [7]:
a1

array([[  3, 656,  46],
       [  6,   9,  55],
       [  2,  67,  34]])

In [56]:
a1.argmax()

1

In [58]:
a1.argmin()

6

In [60]:
a1.argsort()

array([[0, 2, 1],
       [0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [62]:
a1.argmax(axis=0)

array([1, 0, 1], dtype=int64)

In [64]:
a1.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [ ]:
a1.argsort(axis=1)

a1

In [9]:
a1.ravel()

array([  3, 656,  46,   6,   9,  55,   2,  67,  34])

In [11]:
a1.size

9

In [27]:
a1.reshape(9,1)

array([[  3],
       [656],
       [ 46],
       [  6],
       [  9],
       [ 55],
       [  2],
       [ 67],
       [ 34]])

#### NumPy Operation ----- * Arithematic Operation

In [41]:
a=np.array([[2,4,1],[4,2,6],[1,2,3]]); a

array([[2, 4, 1],
       [4, 2, 6],
       [1, 2, 3]])

In [43]:
b=np.array([[1,2,3],[0,9,8],[7,8,0]]); b

array([[1, 2, 3],
       [0, 9, 8],
       [7, 8, 0]])

In [45]:
a+b

array([[ 3,  6,  4],
       [ 4, 11, 14],
       [ 8, 10,  3]])

In [47]:
a-b

array([[ 1,  2, -2],
       [ 4, -7, -2],
       [-6, -6,  3]])

In [49]:
a*b

array([[ 2,  8,  3],
       [ 0, 18, 48],
       [ 7, 16,  0]])

In [53]:
a/b      # Warning on division by zero, but not an error!

C:\Users\NITIN\AppData\Local\Temp\ipykernel_5748\812980504.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b      # Warning on division by zero, but not an error!


array([[2.        , 2.        , 0.33333333],
       [       inf, 0.22222222, 0.75      ],
       [0.14285714, 0.25      ,        inf]])

In [55]:
a**2

array([[ 4, 16,  1],
       [16,  4, 36],
       [ 1,  4,  9]])

In [57]:
np.sqrt(a)

array([[1.41421356, 2.        , 1.        ],
       [2.        , 1.41421356, 2.44948974],
       [1.        , 1.41421356, 1.73205081]])

In [59]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [0.        , 3.        , 2.82842712],
       [2.64575131, 2.82842712, 0.        ]])

In [63]:
a.sum()

25

In [67]:
a.max()

6

In [69]:
b.min()

0

#### Finding element in array --------------------

In [89]:
a=np.array([[1,2,3],[4,5,6],[7,1,0]]); a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [95]:
np.where(a>4)

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [101]:
print(a[a>4])

[5 6 7]


In [105]:
type(np.where(a>4))

tuple

In [107]:
np.count_nonzero(a)

8

In [113]:
np.count_nonzero(a==0)

1